# Generated by Django 5.0.6 on 2024-06-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='des',
            field=models.CharField(default=1, max_length=200, verbose_name='description'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestForeignkey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('foreignkey_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TestModel.test')),
            ],
        ),
    ]
