# Generated by Django 5.0.6 on 2024-06-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_test_des_testforeignkey'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='product',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('id_user', models.IntegerField()),
        #         ('id_Xu', models.IntegerField()),
        #         ('ename', models.CharField(max_length=200)),
        #         ('lname', models.CharField(max_length=200)),
        #         ('fname', models.CharField(max_length=200)),
        #         ('zname', models.CharField(max_length=200)),
        #         ('print_name', models.CharField(max_length=100)),
        #         ('extra_name', models.CharField(max_length=1000)),
        #         ('edes', models.CharField(max_length=1000)),
        #         ('ldes', models.CharField(max_length=1000)),
        #         ('fdes', models.CharField(max_length=1000)),
        #         ('img', models.CharField(max_length=200)),
        #         ('color', models.CharField(max_length=100)),
        #         ('price', models.DecimalField(decimal_places=2, max_digits=8)),
        #         ('price2', models.DecimalField(decimal_places=2, max_digits=8)),
        #         ('price_extra', models.CharField(max_length=2000)),
        #         ('TVA_country', models.CharField(max_length=200)),
        #         ('TVA', models.DecimalField(decimal_places=2, max_digits=8)),
        #         ('extra_TVA', models.DecimalField(decimal_places=2, max_digits=8)),
        #         ('time_supply', models.IntegerField()),
        #         ('soldout', models.BooleanField()),
        #         ('min_nbr', models.IntegerField()),
        #         ('rid', models.IntegerField()),
        #         ('stb', models.IntegerField()),
        #         ('position', models.IntegerField()),
        #         ('favourite', models.IntegerField()),
        #         ('follow_id', models.IntegerField()),
        #         ('extra_id', models.IntegerField()),
        #         ('Xu_class', models.CharField(max_length=200)),
        #         ('custom', models.CharField(max_length=200)),
        #         ('custom2', models.CharField(max_length=200)),
        #         ('custom3', models.CharField(max_length=200)),
        #         ('custom4', models.CharField(max_length=200)),
        #         ('custom5', models.CharField(max_length=200)),
        #         ('print_to_where', models.IntegerField()),
        #         ('cid', models.IntegerField()),
        #         ('option_id', models.IntegerField()),
        #     ],
        #     options={
        #         'db_table': 'product',
        #     },
        # ),
    ]
