# Generated by Django 5.0.6 on 2024-06-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='test',
            table='Test',
        ),
        migrations.AlterModelTable(
            name='testforeignkey',
            table='TestForeignkey',
        ),
    ]
