# Generated by Django 5.0.6 on 2024-08-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='site_wide_discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('discount', models.CharField(max_length=200)),
                ('rid', models.IntegerField(db_comment='restaurant id')),
            ],
            options={
                'db_table': 'site_wide_discount',
                'managed': False,
            },
        ),
    ]
