# Generated by Django 5.0.6 on 2024-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0004_product_tva_id_product_bill_content_product_bill_des_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='post_images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
