# Generated by Django 5.0.6 on 2024-07-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0006_alter_testimg_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/test_images/%Y/%m'),
        ),
    ]
