# Generated by Django 5.0.6 on 2024-06-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
