# Generated by Django 5.0.6 on 2024-06-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0005_testimg_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testimg',
            table='testimg',
        ),
    ]
