# Generated by Django 5.0.6 on 2024-08-01 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0009_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'managed': False},
        ),
    ]
