# Generated by Django 5.0.6 on 2024-08-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0010_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
