# Generated by Django 5.0.6 on 2024-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PosBack', '0011_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('country', models.CharField(choices=[('Belgium', 'Belgium'), ('France', 'France')], default='Belgium', max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'User',
                'ordering': ['date_joined'],
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
