import { notesUnderID } from "./otherText"

export const ChineseText={
    'country':{
        'Belgium':'比利时',
        'France':'法国', 
    }, 
    'sidebar':{
        'title':'侧栏',
        'home':'主页',
        'addCategory':'添加类别',
        'addProduct':'添加产品',
        'editDiscount':'全场折扣', 
    },
    'login':{
        'title':'登录', 
        'loginSucceed':'登陆成功',
        'loginFailed':'用户名或密码不正确',
        'username':'用户名',
        'password':'密码', 
        'loginButton':'登录'
    },
    'logout':{
        'logoutButton':'登出',
        'logoutFailed':'登出失败',
    },
    'product':{
        'id_Xu':['ID', '输入产品ID', 'ID已存在在菜单中', notesUnderID.Chinese],
        'notesForPrintContent':['您可以在下面两个输入框中输入<b>最多25个字符（12个中文）</b>'], 
        'bill_content':['账单内容', '输入显示在 “账单” 中的内容'],
        'kitchen_content':['厨房内容', '输入发送给 “厨房” 的内容'],
        'price':['价格', '输入堂食价格'],
        'price2':['外卖价格', '输入外卖价格'],
        'TVA_country':['国家', '选择您所在的国家'],
        'TVA_category':['TVA（税）'],
        'fetchTVAFailed':'获取TVA数据失败', 
        'cid':['产品类别', '选择产品类别',''],
        'fetchCategoriesFailed':'获取类别失败', 
        'time_supply':['供应时间', ['午餐', '晚餐'], '请选择至少一个供应时间'],
        'print_to_where':['打印机选择','','请选择至少一个打印机'], 
        'fetchPrintersFailed':'获取打印机失败',
        'advanceButton':'高级设置', 
        'returnNormalButton':'返回一般设置', 
        'submitButton':'保存', 
        'Xu_class':['导出到文件'], 
        'dinein_takeaway':['添加到',['堂食菜单','外带菜单','堂食和外带']],
        'add':{
            'pageName':'添加产品',
            'addSuccess':'产品添加成功', 
            'addFailed':'产品添加失败', 
        },
        'check':{
            'pageName':'查看产品', 
            'editButton':'编辑',
        },
        'edit':{
            'pageName':'编辑产品',
            'editSuccess':'编辑成功',
            'editFailed':'编辑失败',
        }, 
        'delete':{
            'deleteButton':'删除', 
            'cancelButton':'取消', 
            'deleteSuccess':['产品 ', ' 删除成功！'],
            'deleteFailed':['产品 ', ' 删除失败！'],
            'confirmDelete':'您确定要删除这个产品吗?',  
        }
        
    },
    'productAdvance':{
        'id_user':['自定义ID', '没有任何限制的自定义ID'],
        'online_content':['在线内容', '请输入在线应用中显示的产品内容'],
        'online_des':['在线描述', '请输入在线应用中显示的产品描述'], 
        'product_type':['产品类型',{
            '产品':0,
            '选项':1,
        }],
        'min_nbr':['最少购买数量','当用户选择购买产品时，用户购买产品的最少数量'],
        'discount':['折扣', ['无', '买一送一','固定降价', '百分比降价']], 
        'allergen':['过敏原'], 
        'ename':['英文名字', '输入英文名字'],
        'lname':['荷兰语名字', '输入荷兰语名字'], 
        'fname':['法语名字', '输入法语名字'], 
        'zname':['中文名字', '输入中文名字'], 
        'edes':['英文描述', '输入英文描述'],
        'ldes':['荷兰语描述', '输入荷兰语描述'],
        'fdes':['法语描述', '输入法语描述'],
        'stb':['Sushi to bar'],
        'favourite':['热门'],
        'cut_group':['切割组'],
        'soldout':['售尽'], 
        'submitButton':'保存', 
    },
    'category':{
        'id':['ID', '输入类别ID', 'ID已存在', notesUnderID.Chinese],
        'name':['类别名字', '输入新的类别名字', '类别已存在'],
        'des':['类别描述', '输入对新的类别的描述'],
        'time_supply':['供应时间', ['午餐', '晚餐'], '请选择至少一个供应时间'], 
        'Xu_class':['ab类别'],
        'nameExisted':'类别名字已存在！', 
        'advanceButton':'高级设置', 
        'returnNormalButton':'返回一般设置', 
        'submitButton':'保存', 
        'add':{
            'pageName':'添加类别',
            'addSuccess':'类别添加成功！', 
            'addFailed':'类别添加失败！', 
        }, 
        'check':{
            'pageName':'检查类别', 
            'editButton':'编辑',
        },
        'edit':{
            'pageName':'编辑类别',
            'editSuccess':'编辑成功！',
            'editFailed':'编辑失败！',
        }, 
        'delete':{
            'deleteButton':'删除', 
            'cancelButton':'取消', 
            'deleteSuccess':['类别 ', ' 删除成功.'],
            'deleteFailed':['类别 ', ' 删除失败.'],
            'confirmDelete':'您确定要删除这个类别吗?',        
        }
    }, 
    'categoryAdvance':{
        'ename':['英文名字', '输入英文名字'],
        'lname':['荷兰语名字', '输入荷兰语名字'], 
        'fname':['法语名字', '输入法语名字'], 
        'zname':['中文名字', '输入中文名字'], 
        'edes':['英文描述', '输入英文描述'],
        'ldes':['荷兰语描述', '输入荷兰语描述'],
        'fdes':['法语描述', '输入法语描述'],
        'submitButton':'保存', 
    },
    'advanceTitle':'高级设置',
    'normalTitle':'一般设置',
    'img':{
        'check':'您已选择的图片：',
        'chooseImg':'选择产品的图片', 
        'changeImg':'更改图片', 
    }, 
    'color':{
        'bgcolor':'选择背景颜色: ',
        'text_color':['自动设置字体颜色', ['黑色', '白色']], 
        'textDefault':'文本', 
    }, 
    'home':{
        'id':['ID'],
        'online_content':['在线内容'],
        'bill_content':['账单内容'],
        'kitchen_content':['厨房内容'],
        'online_des':['账单描述'], 
        'price':['价格'],
        'price2':['外卖价格'],
        'TVA':['TVA'],
        'product_type':['类型'],
        'cid':['产品种类'],
        'time_supply':['供应时间',['午餐', '晚餐', '全天']],
        'print_to_where':['打印机选择'], 
        'noImg':'未选择图片', 
        'title':'主页',
        // 'productList':'产品列表', 
        'DineinMenu':'堂食菜单', 
        'DineinMenuButton':'堂食', 
        'TakeawayMenu':'外卖菜单', 
        'TakeawayMenuButton':'外卖', 
        'modifyOrder':'修改产品顺序',
        'changeFavouriteFailed':'修改收藏失败'
    },
    'dialogChangeOrder':{
        'title':'修改产品顺序',
        'submitButton':'保存',
        'cancelButton':'取消', 
    }, 
    'sideWideDiscount':{
        'pageName':'编辑全场折扣',
        'consumption':['消费满','','消费额度未填写'],
        'discount':['减免','','减免金额未填写'],
        'saveButton':'保存',
        'saveSuccess':'保存成功',
        'saveFailed':'保存失败',
        'deleteButton':'删除',
        'deleteSuccess':'删除成功', 
        'deleteFailed':'删除失败', 
        'discountType':{
            'default':'选择一个打折类型', 
            'fixed':'固定降价',
            'percentage':'百分比降价', 
        }
    }, 
    'export':{
        'chooseButton':['导出', '到文件夹', '成压缩包'],
        'exportButton':'导出', 
        'exportSucceed':'文件导出成功!', 
        'exportfailed':'文件导出失败',
    }, 
    'import':{
        'importButton':'导入',
        'failedText':{
            'failedProduct':'产品添加出现错误',
            'specialAb':'获取特殊ab.txt出现错误',
            'tva':['获取产品TVA出现错误', 'TVA不存在'],
            'printerNull':'产品打印机为空',
            'printerNoExist':'打印机不存在', 
        }, 
        'allImportSucceed':'所有产品添加成功',
        'loading':'导入中', 
    }, 
    'changeExportRule':{
        'button':'修改导出规则',
        'updateFailed':'更新失败', 
        'allUpdateSucceed':'更新成功', 
        'fileNameInvalide':'文件不正确，请选择"HooftName.txt"',
    },
    'returnButton':'返回', 
    'selectLanguage':'语言', 
}


export const ChineseAllergen = {
    'gluten':'含有麸质的谷物', 
    'crustacean':'甲壳动物产品', 
    'egg':'蛋类产品', 
    'peanut':'花生类产品', 
    'fish':'鱼类产品', 
    'soya':'大豆制品', 
    'milk':'奶制品（包括乳糖）', 
    'nut':'坚果及其制品', 
    'celery':'芹菜制品', 
    'mustard':'芥末产品', 
    'sesame':'芝麻制品', 
    'sulfur':'二氧化硫和亚硫酸盐浓度超过 10 毫克/千克或 10 毫克/升', 
    'lupin':'羽扇豆产品',
    'molluscs':'软体动物产品', 
}